# Generated by Django 4.2.3 on 2023-07-28 16:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('first_release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000, message='Enter Valid Year'), django.core.validators.MaxValueValidator(2999, message='Enter Valid Year')])),
                ('no_of_albums_released', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('rnb', 'R&B'), ('jazz', 'Jazz'), ('classic', 'Classic'), ('Contry', 'Contry'), ('rock', 'Rock')], default='rnb', max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.artist')),
            ],
        ),
    ]
