# Generated by Django 4.2.3 on 2023-07-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('rnb', 'R&B'), ('classic', 'Classic'), ('country', 'Country'), ('jazz', 'Jazz'), ('rock', 'Rock')], default='rnb', max_length=10),
        ),
    ]
