# Generated by Django 4.2.3 on 2023-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('classic', 'Classic'), ('rock', 'Rock'), ('country', 'Country'), ('jazz', 'Jazz'), ('rnb', 'R&B')], default='rnb', max_length=10),
        ),
    ]
