# Generated by Django 4.2.3 on 2023-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('classic', 'Classic'), ('rock', 'Rock'), ('rnb', 'R&B'), ('country', 'Country'), ('jazz', 'Jazz')], default='rnb', max_length=10),
        ),
    ]
