# Generated by Django 4.2.3 on 2023-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('rnb', 'R&B'), ('rock', 'Rock'), ('country', 'Country'), ('jazz', 'Jazz'), ('classic', 'Classic')], default='rnb', max_length=10),
        ),
    ]
